### ISSUE TITLE
Prevent Outbox behavior from creating large amounts of duplicates when RU limits have been reached

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Persistence.CosmosDB#170]
As part of the Outbox process, the last step is to mark the dispatched outgoing messages as dispatched in the Outbox storage. However, this operation might run into an exception in case the provisioned RUs have been exceeded when the system is under heavy load (this might easily be the case when combining CosmosDB persistence with auto-scaling hosting options like Azure Functions). When Azure throttles the client due to exceeded RU capacity, the exception thrown will make NServiceBus to retry the message while the outgoing message has already been dispatched to the transport as there is no distributed transaction.
Retrying the message will continue to create duplicate messages for the same outbox record while the system stays under heavy load.

It seems the read operations that happen first as part of the Outbox process are less likely to hit the RU limits due to lower RU costs compared to the involved update operation (especially when trying to update multiple records when there are multiple outgoing messages).

It would be desirable to minimize the amount of duplicate messages, e.g. by throttling the endpoint processing once 429 status code errors have been received. Additionally, better feedback and guidance might be helpful in case users run into such situations.

### Triage

This triage checklist should be filled in by a staff member from Particular Software.

| Yes / No | Triage criteria          |
|--------|--------------------------------|
| Hard to estimate, potentially No       | The expected effort to code and document the enhancement is less than 8 hours. |
| Hard to estimate, potentially No      | A reviewer can approve any changes in less than 1 hour. |
| No       | The solution is obvious and does not require analysis by a [task force](https://particular.net/careers/work-culture). |
| Yes       | The issue is **NOT** blocking the customer from using the Preview in production. |
| No       | The issue is blocking the user from using the Preview in production. |
| Personally I'm aware of one user running into this scenario.       | There's evidence solving the problem will benefit multiple users. |

**Comment by SeanFeldman** [comment]
> It would be desirable to minimize the amount of duplicate messages, e.g. by throttling the endpoint processing once 429 status code errors have been received.

@timbussmann, NServiceBus doesn't allow dynamic processing adjustments, does it?

**Comment by timbussmann** [comment]
@SeanFeldman core doesn't have a way to throttle a transport in some way directly, no. Instead of asking the transport to slow down, a workaround might just be to increase processing time which can be done by any "actor" (transport, core, persistence, plugins,...).

**Comment by SeanFeldman** [comment]
Asking a transport to slow down is not an option I'm aware of in NServiceBus transport seam. Unless that has changed in v8.
Increasing processing time is undesirable for transport such as ASB where a message is leased and increased processing time will cause other types of issues (lost lock exceptions for example). Definitely, something to think about. Thanks.

**Comment by timbussmann** [comment]
> Increasing processing time is undesirable for transport such as ASB where a message is leased and increased processing time will cause other types of issues (lost lock exceptions for example)

what's the default lease time we use? Isn't this around 30 sec? The slow down should probably be somewhere in the sub-second to second ballpark assuming that RUs reset per second? The major risk there would be prefetching I guess?

**Comment by SeanFeldman** [comment]
> what's the default lease time we use? Isn't this around 30 sec?

5 minutes.
This is probably getting into the territory of solutioning, which I'll purposely stay out of.

**Comment by vince-nyanga** [comment]
We experienced this issue in one of our applications. We had thousands of the exact same message in our queue.

**Comment by SeanFeldman** [comment]
CosmosDB has a header (accessible as `x-ms-retry-after-ms` or `response.Headers["x-ms-retry-after-ms"]` in C#) that indicates what the throttling time in milliseconds is.

> `x-ms-retry-after-ms` The number of milliseconds to wait to retry the operation after an initial operation received HTTP status code 429 and was throttled.

This could help the persistence to "manually" retry the operation rather than rely on transport retries and cause more pressure on CosmosDB with unnecessary idempotency checks and additional reads to fetch the stored dispatch operations that need to be actioned.

**Comment by airmanx86** [comment]
A paying customer of NSB here and first time trying to use outbox with CosmosDB. We are using v1.0 of the package and run into this issue. On the handler which use Cosmos persisitece, large number of phyiscally duplicated messages are created on the transport very quickly (while logically the same message on NSB). On the next handler, because the commands which are already dispatched are reprocessed, it resulted in logically duplicate messages. Basically, if not all the handlers are idempotent and deterministic, the outbox cannot be used. Even if the handlers are idempotent the scalability is hugely impacted by this problem.

I have done some tests to explore this issue. On 400RU limit with outbox turn on:
1. it takes approx 150 queued messages operating on the same partition to cause HTTP 429 for no / cheap access to CosmosDB.
2. when the system is busy, if the CosmosDB access is about 20RU+, HTTP 429 is basically happening all the time

Processing 1000 messages which require 40RU CosmosDB access each:
1. with outbox - it generated 200+ duplicated messages
2. without outbox - it geenrated no duplicate messages and finish processing faster than outbox

We have since then turn off outbox

**Comment by airmanx86** [comment]
One our developer is suspecting the code which read the outbox record is not able to handle HTTP 429

```
        public static async Task<OutboxRecord> ReadOutboxRecord(this Container container, string messageId, PartitionKey partitionKey, JsonSerializer serializer, ContextBag context, CancellationToken cancellationToken = default)
        {
            var responseMessage = await container.ReadItemStreamAsync(messageId, partitionKey, cancellationToken: cancellationToken)
                .ConfigureAwait(false);

            if (responseMessage.StatusCode == HttpStatusCode.NotFound || responseMessage.Content == null)
            {
                return default;
            }
```

https://github.com/Particular/NServiceBus.Persistence.CosmosDB/blob/8fdb48bda4dedb52b1f0b0ec56975baa26c64508/src/NServiceBus.Persistence.CosmosDB/Outbox/OutboxContainerExtensions.cs#L13-L18

**Comment by airmanx86** [comment]
We have also implemented custom recoverability policy to randomly delay retry message immediately when we see HTTP 429 coming from Cosmos DB

**Comment by timbussmann** [comment]
thanks, @airmanx86 for the additional information 👍 

Until this is improved, I'd recommend to increase the provisioned RUs or to switch to the serverless pricing model to avoid running into the 429 error codes.

**Comment by Ivan-L** [comment]
We have also implemented a custom recoverability policy which looks for `CosmosException` and specifically the `TooManyRequests` status code. It delays the retry using the `RetryAfter` timespan:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosexception.retryafter?view=azure-dotnet

That being said, perhaps the NServiceBus Outbox persister can implement such logic (if agreed) when persisting the dispatched outbox record?

From a Cosmos DB throughput perspective, we cannot switch to the serverless pricing model as it lacks support for replicating data across multiple regions, which we need. We also cannot guarantee that we will never get throttled using the provisioned throughput model even when using auto-scaled throughput, though increasing the maximum RU/s to a higher number (and paying more for this) does reduce the likelihood of being throttled.

**Comment by DavidBoike** [comment]
Previously we were thinking about this issue as an enhancement. Given the number of you that are having trouble with it that is preventing you from using the Outbox at all, we have now begun to think about it as a bug. We've triaged it as a priority bug and have put it in the queue to be fixed.

**Comment by danielmarbach** [comment]
@Ivan-L @airmanx86 We have started looking into this yesterday from the perspective of throttling of CosmosDB operations in general, as well as what the persister could or should do. We would like to share a few thoughts with you and hopefully get your inputs here. 

When using CosmosDB with provisioned throughput, ultimately every operation issued against Cosmos can be throttled. So regardless whether NServiceBus uses your CosmosDB instance under the hood or your code operates on top of Cosmos the code needs to deal with throttling. Because of this being a cross-cutting concern, the client SDK has built in handling for throttling. This is how it would work when you provide us the client

```
endpointConfiguration.UsePersistence<CosmosPersistence>()
    .CosmosClient(new CosmosClient(connectionString, new CosmosClientOptions
            {
                MaxRetryAttemptsOnRateLimitedRequests = numberOfAttempts,
                MaxRetryWaitTimeOnRateLimitedRequests = TimeSpan.From..()
            });
```

the same can be done when using the builder

```
var builder = new CosmosClientBuilder(connectionString);
builder.WithThrottlingRetryOptions(maxRetryWaitTimeOnThrottledRequests: TimeSpan.From..(),
                maxRetryAttemptsOnThrottledRequests: numberOfAttempts);

endpointConfiguration.UsePersistence<CosmosPersistence>().CosmosClient(builder.Build());
```

Once that is in place, the client uses the provided configuration to handle 429 retry attempts and also respects the retry after delay interval. Failures will then only be raised upwards as the configured thresholds are reached.

Given it is possible to control this behavior by your application code in a cross-cutting way, we think it is best to not try to add custom logic to the persister to deal with it. We are thinking to add a sample that demonstrates how to deal with throttling and link that in the documentation instead. What are your thoughts?

We have also considered adding a default behavior in the case when the persistence manages the cosmos client as well as a request handler middleware that logs 429. The problem with this approach though is the following:

- It is hard to say what sane defaults would be since it is entirely up to the application load and provisioned RUs
- Logging can have performance and throughput consequences on the endpoint
- For customers using serverless mode, these changes might not even matter
- For other customers we might end up exposing configuration options to influence the defaults of the persistence managed cosmos client, which then closely resembles the options of the SDK, i.ex. `endpointConfiguration.UsePersistence<CosmosPersistence>()Throttling().SetMaxRetryAttemptsOnRateLimitedRequests(numberOfAttempts)`

In general we are trying to use the SDK types as close as possible with their defaults when the persister manages them and for all other cases allow the SDK type creation to be overriden by passing a configured instance or letting a configured instance to be injected.

**Comment by danielmarbach** [comment]
We have started a [pull request](https://github.com/Particular/docs.particular.net/pull/5577) documenting the throttling behavior and the mitigation strategies using examples in how to configure the client as well as linking the official documentation.

**Comment by danielmarbach** [comment]
We have merged the documentation. Corresponding guidance is available at

https://docs.particular.net/persistence/cosmosdb/#provisioned-throughput-rate-limiting

we have also added similar guidance to the table persistence that enables the usage of the cosmos table API

https://docs.particular.net/persistence/azure-table/#provisioned-throughput-rate-limiting-with-azure-cosmos-db
