### ISSUE TITLE
Throw an exception that provides information about all the operations that failed within the batch instead of the first one

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.Persistence.CosmosDB#68]
Currently, we throw TransactionalBatchOperationException that gives access to the `TransactionalBatchOperationResult` of the first operation that failed
Technically we could collect all the failures and then throw some sort of an aggregate exception, for example, rename `TransactionalBatchOperationException` to `TransactionalBatchOperationsException` and there expose a list of `TransactionalBatchOperationResult` or even better have `TransactionalBatchOperationsException` have a list of TransactionalBatchOperationException because that would allow us to expose also a message with some addition reasons
Alternatively, `TransactionalBatchOperationsException` could expose "tuples" of string and `TransactionalBatchOperationResult` which I find a bit weird honestly

**Comment by danielmarbach** [comment]
We checked the behavior of Cosmos and it looks like if one conflict occurs the first operation result indicates conflict and all others return 424 (Failed Dependency). Therefore the current behavior of throwing for the first entry that has an actual status code that is not 424 makes sense at this point.

**Comment by aleksandr-samila** [comment]
I used [this sample](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/TransactionalBatch/Program.cs) as a base for the validation. Actually, I just commented on a few lines of code to generate conflicts and I can second the statement from [here](https://github.com/Particular/NServiceBus.Persistence.CosmosDB/issues/68#issuecomment-705108893).
So, currently, because of the nature of the CosmosDB implementation, there is no reason to implement the [original request](https://github.com/Particular/NServiceBus.Persistence.CosmosDB/issues/68).
Maybe, in the future if/when the original CosmosDB behavior changes we can back to this issue once again, but not now.
